import { SupportedChain } from "@/helpers/interfaces/api";

export const supportedChains: Array<SupportedChain> = [
  {
    id: "algorand",
    symbol: "algo",
    name: "Algorand",
    web_slug: "algorand",
    categories: [
      "Multicoin Capital Portfolio",
      "Proof of Stake (PoS)",
      "DWF Labs Portfolio",
      "Alleged SEC Securities",
      "Cryptocurrency",
      "Smart Contract Platform",
      "Layer 1 (L1)",
      "Algorand Ecosystem",
    ],
    description: {
      en: "Algorand is a scalable, secure and decentralized digital currency and transactions platform.",
    },
    links: {
      homepage: ["https://algorand.foundation/", "https://www.algorand.com/", "https://www.algorand.com/resources"],
      whitepaper: "https://www.algorand.com/technology/white-papers",
      blockchain_site: ["https://allo.info/", "https://explorer.perawallet.app/", "", "", "", "", "", "", "", ""],
    },
    image: {
      thumb: "https://assets.coingecko.com/coins/images/4380/thumb/download.png?1696504978",
      small: "https://assets.coingecko.com/coins/images/4380/small/download.png?1696504978",
      large: "https://assets.coingecko.com/coins/images/4380/large/download.png?1696504978",
    },
  },
  {
    id: "bitcoin",
    symbol: "btc",
    name: "Bitcoin",
    web_slug: "bitcoin",
    categories: ["FTX Holdings", "Cryptocurrency", "Proof of Work (PoW)", "Layer 1 (L1)"],
    description: {
      en: 'Bitcoin is the first successful internet money based on peer-to-peer technology; whereby no central bank or authority is involved in the transaction and production of the Bitcoin currency. It was created by an anonymous individual/group under the name, Satoshi Nakamoto. The source code is available publicly as an open source project, anybody can look at it and be part of the developmental process.\r\n\r\nBitcoin is changing the way we see money as we speak. The idea was to produce a means of exchange, independent of any central authority, that could be transferred electronically in a secure, verifiable and immutable way. It is a decentralized peer-to-peer internet currency making mobile payment easy, very low transaction fees, protects your identity, and it works anywhere all the time with no central authority and banks.\r\n\r\nBitcoin is designed to have only 21 million BTC ever created, thus making it a deflationary currency. Bitcoin uses the <a href="https://www.coingecko.com/en?hashing_algorithm=SHA-256">SHA-256</a> hashing algorithm with an average transaction confirmation time of 10 minutes. Miners today are mining Bitcoin using ASIC chip dedicated to only mining Bitcoin, and the hash rate has shot up to peta hashes.\r\n\r\nBeing the first successful online cryptography currency, Bitcoin has inspired other alternative currencies such as <a href="https://www.coingecko.com/en/coins/litecoin">Litecoin</a>, <a href="https://www.coingecko.com/en/coins/peercoin">Peercoin</a>, <a href="https://www.coingecko.com/en/coins/primecoin">Primecoin</a>, and so on.\r\n\r\nThe cryptocurrency then took off with the innovation of the turing-complete smart contract by <a href="https://www.coingecko.com/en/coins/ethereum">Ethereum</a> which led to the development of other amazing projects such as <a href="https://www.coingecko.com/en/coins/eos">EOS</a>, <a href="https://www.coingecko.com/en/coins/tron">Tron</a>, and even crypto-collectibles such as <a href="https://www.coingecko.com/buzz/ethereum-still-king-dapps-cryptokitties-need-1-billion-on-eos">CryptoKitties</a>.',
    },
    links: {
      homepage: ["http://www.bitcoin.org", "", ""],
      whitepaper: "https://bitcoin.org/bitcoin.pdf",
      blockchain_site: [
        "https://mempool.space/",
        "https://blockchair.com/bitcoin/",
        "https://btc.com/",
        "https://btc.tokenview.io/",
        "https://www.oklink.com/btc",
        "https://3xpl.com/bitcoin",
        "",
        "",
        "",
        "",
      ],
    },
    image: {
      thumb: "https://assets.coingecko.com/coins/images/1/thumb/bitcoin.png?1696501400",
      small: "https://assets.coingecko.com/coins/images/1/small/bitcoin.png?1696501400",
      large: "https://assets.coingecko.com/coins/images/1/large/bitcoin.png?1696501400",
    },
  },
  {
    id: "ethereum",
    symbol: "eth",
    name: "Ethereum",
    web_slug: "ethereum",
    categories: [
      "FTX Holdings",
      "Multicoin Capital Portfolio",
      "Proof of Stake (PoS)",
      "Smart Contract Platform",
      "Layer 1 (L1)",
      "Ethereum Ecosystem",
    ],
    description: {
      en: "Ethereum is a global, open-source platform for decentralized applications. In other words, the vision is to create a world computer that anyone can build applications in a decentralized manner; while all states and data are distributed and publicly accessible. Ethereum supports smart contracts in which developers can write code in order to program digital value. Examples of decentralized apps (dapps) that are built on Ethereum includes tokens, non-fungible tokens, decentralized finance apps, lending protocol, decentralized exchanges, and much more.\r\n\r\nOn Ethereum, all transactions and smart contract executions require a small fee to be paid. This fee is called Gas. In technical terms, Gas refers to the unit of measure on the amount of computational effort required to execute an operation or a smart contract. The more complex the execution operation is, the more gas is required to fulfill that operation. Gas fees are paid entirely in Ether (ETH), which is the native coin of the blockchain. The price of gas can fluctuate from time to time depending on the network demand.",
    },
    links: {
      homepage: ["https://www.ethereum.org/", "", ""],
      whitepaper: "",
      blockchain_site: [
        "https://etherscan.io/",
        "https://ethplorer.io/",
        "https://blockchair.com/ethereum",
        "https://eth.tokenview.io/",
        "https://www.oklink.com/eth",
        "https://3xpl.com/ethereum",
        "",
        "",
        "",
        "",
      ],
    },
    image: {
      thumb: "https://assets.coingecko.com/coins/images/279/thumb/ethereum.png?1696501628",
      small: "https://assets.coingecko.com/coins/images/279/small/ethereum.png?1696501628",
      large: "https://assets.coingecko.com/coins/images/279/large/ethereum.png?1696501628",
    },
  },
  {
    id: "harmony",
    symbol: "one",
    name: "Harmony",
    web_slug: "harmony",
    categories: ["Binance Launchpad", "Protocol", "Smart Contract Platform", "Harmony Ecosystem"],
    description: {
      en: "Harmony’s open, decentralized network is enabled through the use of the native protocol token - Harmony ONE. The token incentivizes and rewards a variety of participants including developers, validators/stakers, investors, and community members who develop, secure and govern the network. In order to use the network, users pay a small transaction fee denominated in the native Harmony token.\r\n\r\nHarmony’s scalable, high-throughput protocol is powered by a native token which is used for various forms of payment and participation in the protocol (staking, transaction fees, voting & governance).\r\n\r\nHarmony uses blockchain to align incentives of different stakeholders, developers and businesses while allowing them to build open marketplaces of fungible and non-fungible tokens and assets. Furthermore, the upcoming application of zero-knowledge proofs will allow Harmony to become a data sharing platform that can overcome the conflicting problem plaguing many information and data markets: that individual market participants’ have mutual distrust to share data but strong desire to acquire data themselves.\r\n\r\nThe Harmony token will function in the following aspects of the protocol:\r\n\r\nThe token is used for staking, which is necessary to participate in the POS consensus & earn block rewards and transaction fees.\r\nThe token is used to pay for transaction fees, gas and storage fees.\r\nThe token is used in voting for on-chain governance of the protocol.",
    },
    links: {
      homepage: ["https://harmony.one/", "", ""],
      whitepaper: "https://harmony.one/whitepaper",
      blockchain_site: ["https://explorer.harmony.one/", "", "", "", "", "", "", "", "", ""],
    },
    image: {
      thumb: "https://assets.coingecko.com/coins/images/4344/thumb/Y88JAze.png?1696504947",
      small: "https://assets.coingecko.com/coins/images/4344/small/Y88JAze.png?1696504947",
      large: "https://assets.coingecko.com/coins/images/4344/large/Y88JAze.png?1696504947",
    },
  },
  {
    id: "cosmos",
    symbol: "atom",
    name: "Cosmos Hub",
    web_slug: "cosmos-hub",
    categories: [
      "Osmosis Ecosystem",
      "Kava Ecosystem",
      "Proof of Stake (PoS)",
      "Alleged SEC Securities",
      "Cryptocurrency",
      "Paradigm Portfolio",
      "Cosmos Ecosystem",
      "BNB Chain Ecosystem",
      "Layer 1 (L1)",
      "Canto Ecosystem",
    ],
    description: {
      en: "The Cosmos network consists of many independent, parallel blockchains, called zones, each powered by classical Byzantine fault-tolerant (BFT) consensus protocols like Tendermint (already used by platforms like ErisDB). Some zones act as hubs with respect to other zones, allowing many zones to interoperate through a shared hub. The architecture is a more general application of the Bitcoin sidechains concept, using classic BFT and Proof-of-Stake algorithms, instead of Proof-of-Work.Cosmos can interoperate with multiple other applications and cryptocurrencies, something other blockchains can’t do well. By creating a new zone, you can plug any blockchain system into the Cosmos hub and pass tokens back and forth between those zones, without the need for an intermediary.\r\n\r\nWhile the Cosmos Hub is a multi-asset distributed ledger, there is a special native token called the atom. Atoms have three use cases: as a spam-prevention mechanism, as staking tokens, and as a voting mechanism in governance.\r\n\r\nAs a spam prevention mechanism, Atoms are used to pay fees. The fee may be proportional to the amount of computation required by the transaction, similar to Ethereum’s concept of “gas”. Fee distribution is done in-protocol and a protocol specification is described here.\r\n\r\nAs staking tokens, Atoms can be “bonded” in order to earn block rewards. The economic security of the Cosmos Hub is a function of the amount of Atoms staked. The more Atoms that are collateralized, the more “skin” there is at stake and the higher the cost of attacking the network. Thus, the more Atoms there are bonded, the greater the economic security of the network.\r\n\r\nAtom holders may govern the Cosmos Hub by voting on proposals with their staked Atoms.",
    },
    links: {
      homepage: ["http://cosmos.network/", "", ""],
      whitepaper: "http://cosmos.network/whitepaper",
      blockchain_site: [
        "https://www.mintscan.io/cosmos",
        "https://cosmos.bigdipper.live/",
        "https://hubble.figment.io/cosmos/chains/cosmoshub-4",
        "https://atomscan.com/",
        "https://bscscan.com/token/0x0eb3a705fc54725037cc9e008bdede697f62f335",
        "https://explorer.energi.network/token/0xd821db2439ecf24e5a623079c783e951646da449",
        "https://evm.explorer.canto.io/token/0xeceeefcee421d8062ef8d6b4d814efe4dc898265",
        "https://evm.evmos.org/token/0xc5e00d3b04563950941f7137b5afa3a534f0d6d6",
        "https://atom.tokenview.io/en",
        "https://binplorer.com/address/0x0eb3a705fc54725037cc9e008bdede697f62f335",
      ],
    },
    image: {
      thumb: "https://assets.coingecko.com/coins/images/1481/thumb/cosmos_hub.png?1696502525",
      small: "https://assets.coingecko.com/coins/images/1481/small/cosmos_hub.png?1696502525",
      large: "https://assets.coingecko.com/coins/images/1481/large/cosmos_hub.png?1696502525",
    },
  },
  {
    id: "filecoin",
    symbol: "fil",
    name: "Filecoin",
    web_slug: "filecoin",
    categories: ["DePIN", "Alleged SEC Securities", "Infrastructure", "Storage", "Layer 1 (L1)"],
    description: {
      en: "The Filecoin network achieves staggering economies of scale by allowing anyone worldwide to participate as storage providers. It also makes storage resemble a commodity or utility by decoupling hard-drive space from additional services. On this robust global market the price of storage will be driven by supply and demand, not corporate pricing departments, and miners will compete on factors like reputation for reliability as well as price.",
    },
    links: {
      homepage: ["https://filecoin.io/", "", ""],
      whitepaper: "",
      blockchain_site: [
        "https://filfox.info/en",
        "https://filscan.io/#/tipset/chain",
        "https://hecoinfo.com/token/0xae3a768f9ab104c69a7cd6041fe16ffa235d1810",
        "https://explorer.energi.network/token/0xf8a425e39af1976e1826f0c8843149afa5e9ec04",
        "",
        "",
        "",
        "",
        "",
        "",
      ],
    },
    image: {
      thumb: "https://assets.coingecko.com/coins/images/12817/thumb/filecoin.png?1696512609",
      small: "https://assets.coingecko.com/coins/images/12817/small/filecoin.png?1696512609",
      large: "https://assets.coingecko.com/coins/images/12817/large/filecoin.png?1696512609",
    },
  },
  {
    id: "flow",
    symbol: "flow",
    name: "Flow",
    web_slug: "flow",
    categories: [
      "Multicoin Capital Portfolio",
      "Proof of Stake (PoS)",
      "Alleged SEC Securities",
      "Smart Contract Platform",
      "Sports",
      "NFT",
      "Layer 1 (L1)",
    ],
    description: {
      en: "Flow by Dapper Labs (The company which created CryptoKitties) is a blockchain network that aims to be fast, secure, and developer friendly.\r\n\r\nThe idea for a new blockchain targeting games and social networks was conceived after Ethereum faced large scalability issues as seen with the high transaction fees during the CryptoKitties hype. The Flow team deduced shards and sidechains were not long term solutions for apps that strive for performance.\r\n\r\nInvestors include large backers such as Andreessen Horowitz, Warner Music Group, Union Square Ventures, Digital Currency Group, and more.",
    },
    links: {
      homepage: ["https://flow.com", "", ""],
      whitepaper: "",
      blockchain_site: ["https://www.flowdiver.io", "https://flowscan.org/", "", "", "", "", "", "", "", ""],
    },
    image: {
      thumb:
        "https://assets.coingecko.com/coins/images/13446/thumb/5f6294c0c7a8cda55cb1c936_Flow_Wordmark.png?1696513210",
      small:
        "https://assets.coingecko.com/coins/images/13446/small/5f6294c0c7a8cda55cb1c936_Flow_Wordmark.png?1696513210",
      large:
        "https://assets.coingecko.com/coins/images/13446/large/5f6294c0c7a8cda55cb1c936_Flow_Wordmark.png?1696513210",
    },
  },
  {
    id: "tron",
    symbol: "trx",
    name: "TRON",
    web_slug: "tron",
    categories: [
      "FTX Holdings",
      "DWF Labs Portfolio",
      "Alleged SEC Securities",
      "Tron Ecosystem",
      "Smart Contract Platform",
      "Layer 1 (L1)",
    ],
    description: {
      en: 'What is Tron?\r\nTron\'s mission is to build a truly decentralized internet and aims to be the largest blockchain-based operating system in the world, known as the TRON protocol. The TRON protocol will offer high scalability, high availability, and high throughput computing to serve decentralized applications via smart contracts. Ethereum EVM-based smart contracts will be compatible and deployable on the TRON network as such Solidity developers do not have to rewrite their applications.\r\n\r\nWhy Tron?\r\nSince TRON protocol does not rely on proof of work or mining, instead governed by nodes located around the world, it is decentralized while providing high throughput for transactions on the blockchain. This is suitable for dapps that require high speed transactions especially games. There are a number of tokens already issued on the TRON network and the <a href="https://www.coingecko.com/en/exchanges/trx_market">decentralized exchanges TRX.market</a> has launched.\r\n\r\nOn July 24th 2018, TRON acquired BitTorrent, one of the largest P2P file sharing protocol. As a result of the acquisition, <a href="https://www.coingecko.com/en/coins/bittorrent">BitTorrent Token (BTT)</a> was launched as the cryptocurrency to power the economics on the BitTorrent network. The Token will be used to inceltivize file sharing and storage within the network.\r\n',
    },
    links: {
      homepage: ["https://tron.network", "https://trondao.org/", ""],
      whitepaper: "",
      blockchain_site: [
        "https://tronscan.org/",
        "https://trx.tokenview.io",
        "https://www.oklink.com/trx",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
      ],
    },
    image: {
      thumb: "https://assets.coingecko.com/coins/images/1094/thumb/tron-logo.png?1696502193",
      small: "https://assets.coingecko.com/coins/images/1094/small/tron-logo.png?1696502193",
      large: "https://assets.coingecko.com/coins/images/1094/large/tron-logo.png?1696502193",
    },
  },
  {
    id: "eos",
    symbol: "eos",
    name: "EOS",
    web_slug: "eos",
    categories: ["DWF Labs Portfolio", "Smart Contract Platform"],
    description: {
      en: "Blockchain built and run by the EOS Community.\r\n \r\nThe EOSIO core development is now in the hands of the community:\r\nhttps://medium.com/eos-network-foundation/eosio-coalition-report-april-28th-71d5b77d63cc\r\n \r\nAbout EOS Support:\r\n \r\nhttps://EOSsupport.io is an organisation started by community members that serves as a concierge for providing user and technical support for customers who use the EOS Network.\r\nEOS Support team offers new services such as coordination efforts for the Mandel consensus upgrade, knowledge base, technical support, and many more for the EOS network.\r\nSource: EOS Network Foundation Quarterly Report Q1 2022:\r\nhttps://medium.com/eos-network-foundation/enf-q1-2022-report-5320984367e9\r\nPage 13: https://drive.google.com/file/d/1sL42m5PO-N4BeZUvTa-5w3wU3TQnsp93/view",
    },
    links: {
      homepage: ["https://eosnetwork.com/", "https://eossupport.io", ""],
      whitepaper: "https://eosn.foundation/blog/category/eos-blue-papers/",
      blockchain_site: [
        "https://bloks.io/",
        "https://eospark.com/",
        "https://eosflare.io/",
        "https://eosauthority.com/",
        "",
        "",
        "",
        "",
        "",
        "",
      ],
    },
    image: {
      thumb: "https://assets.coingecko.com/coins/images/738/thumb/eos-eos-logo.png?1696501893",
      small: "https://assets.coingecko.com/coins/images/738/small/eos-eos-logo.png?1696501893",
      large: "https://assets.coingecko.com/coins/images/738/large/eos-eos-logo.png?1696501893",
    },
  },
  {
    id: "cardano",
    symbol: "ada",
    name: "Cardano",
    web_slug: "cardano",
    categories: [
      "Proof of Stake (PoS)",
      "Alleged SEC Securities",
      "Smart Contract Platform",
      "Layer 1 (L1)",
      "Cardano Ecosystem",
    ],
    description: {
      en: "",
    },
    links: {
      homepage: ["https://www.cardano.org/en/home/", "", ""],
      whitepaper: "https://docs.cardano.org/introduction",
      blockchain_site: [
        "https://cardanoscan.io/",
        "https://cardanoexplorer.com/",
        "https://blockchair.com/cardano",
        "https://adaex.org/",
        "https://adastat.net/",
        "https://ada.tokenview.io/",
        "https://3xpl.com/cardano",
        "",
        "",
        "",
      ],
    },
    image: {
      thumb: "https://assets.coingecko.com/coins/images/975/thumb/cardano.png?1696502090",
      small: "https://assets.coingecko.com/coins/images/975/small/cardano.png?1696502090",
      large: "https://assets.coingecko.com/coins/images/975/large/cardano.png?1696502090",
    },
  },
  {
    id: "everscale",
    symbol: "ever",
    name: "Everscale",
    web_slug: "everscale",
    categories: ["BNB Chain Ecosystem", "Ethereum Ecosystem"],
    description: {
      en: "Everscale is a fast, secure and scalable network with near-zero fees, which can process up to a million transactions per second thanks to its unique dynamic sharding technology. The network was originally built off of the Durov brothers' TON concept before launching as a separate entity. The change to Everscale was predicated by the network’s robust development which saw it move way beyond the original technological offerings of TON and build an entire ecosystem around its platforms and products, replete with its own nodes and technology. The ecosystem features a number of products, including a DEX and bridges with other blockchains. ",
    },
    links: {
      homepage: ["https://everscale.network/", "https://flatqube.io/swap", ""],
      whitepaper: "",
      blockchain_site: [
        "https://ever.live/landing",
        "https://etherscan.io/token/0x1ffEFD8036409Cb6d652bd610DE465933b226917",
        "https://ethplorer.io/address/0x1ffefd8036409cb6d652bd610de465933b226917",
        "https://bscscan.com/token/0x0a7e7d210c45c4abba183c1d0551b53ad1756eca",
        "https://flatqube.io/",
        "https://binplorer.com/address/0x0a7e7d210c45c4abba183c1d0551b53ad1756eca",
        "",
        "",
        "",
        "",
      ],
    },
    image: {
      thumb: "https://assets.coingecko.com/coins/images/12783/thumb/everscale_badge_main_round_1x.png?1696512578",
      small: "https://assets.coingecko.com/coins/images/12783/small/everscale_badge_main_round_1x.png?1696512578",
      large: "https://assets.coingecko.com/coins/images/12783/large/everscale_badge_main_round_1x.png?1696512578",
    },
  },
  {
    id: "solana",
    symbol: "sol",
    name: "Solana",
    web_slug: "solana",
    categories: [
      "FTX Holdings",
      "Multicoin Capital Portfolio",
      "Proof of Stake (PoS)",
      "Alleged SEC Securities",
      "Smart Contract Platform",
      "Solana Ecosystem",
      "Layer 1 (L1)",
    ],
    description: {
      en: "Solana is a highly functional open source project that banks on blockchain technology’s permissionless nature to provide decentralized finance (DeFi) solutions. It is a layer 1 network that offers fast speeds and affordable costs. While the idea and initial work on the project began in 2017, Solana was officially launched in March 2020 by the Solana Foundation with headquarters in Geneva, Switzerland.",
    },
    links: {
      homepage: ["https://solana.com/", "", ""],
      whitepaper: "",
      blockchain_site: [
        "https://solscan.io/",
        "https://xray.helius.xyz/",
        "https://solana.fm/",
        "https://solanabeach.io/",
        "https://www.oklink.com/sol",
        "https://explorer.solana.com/",
        "",
        "",
        "",
        "",
      ],
    },
    image: {
      thumb: "https://assets.coingecko.com/coins/images/4128/thumb/solana.png?1696504756",
      small: "https://assets.coingecko.com/coins/images/4128/small/solana.png?1696504756",
      large: "https://assets.coingecko.com/coins/images/4128/large/solana.png?1696504756",
    },
  },
  {
    id: "stellar",
    symbol: "xlm",
    name: "Stellar",
    web_slug: "stellar",
    categories: ["Stellar Ecosystem", "Cryptocurrency", "Smart Contract Platform"],
    description: {
      en: 'The Stellar network is an open source, distributed, and community owned network used to facilitate cross-asset transfers of value. Stellar aims to help facilitate cross-asset transfer of value at a fraction of a penny while aiming to be an open financial system that gives people of all income levels access to low-cost financial services. Stellar can handle exchanges between fiat-based currencies and between cryptocurrencies. Stellar.org, the organization that supports Stellar, is centralized like <a href="https://www.coingecko.com/en/coins/ripple">XRP</a> and meant to handle cross platform transactions and micro transactions like XRP. However, unlike Ripple, Stellar.org is non-profit and their platform itself is open source and decentralized. \r\n\r\nStellar was founded by Jed McCaleb in 2014. Jed McCaleb is also the founder of Mt. Gox and co-founder of Ripple, launched the network system Stellar with former lawyer Joyce Kim. Stellar is also a payment technology that aims to connect financial institutions and drastically reduce the cost and time required for cross-border transfers. In fact, both payment networks used the same protocol initially.\r\n\r\nDistributed Exchange\r\nThrough the use of its intermediary currency Lumens (XLM), a user can send any currency that they own to anyone else in a different currency.\r\n\r\nFor instance, if Joe wanted to send USD to Mary using her EUR, an offer is submitted to the distributed exchange selling USD for EUR. This submitted offer forms is known as an order book. The network will use the order book to find the best exchange rate for the transaction in-order to minimize the fee paid by a user.\r\n\r\nThis multi-currency transaction is possible because of "Anchors". Anchors are trusted entities that hold people’s deposits and can issue credit. In essence, Anchors serves as the bridge between different currencies and the Stellar network.\r\n\r\nLumens (XLM)\r\nLumens are the native asset (digital currency) that exist on the Stellar network that helps to facilitate multi-currency transactions and prevent spams. For multi-currency transactions, XLM is the digital intermediary that allows for such a transaction to occur at a low cost.\r\n\r\nIn-order to prevent DoS attacks (aka spams) that would inevitably occur on the Stellar network, a small fee of 0.00001 XLM is associated with every transaction that occurs on the network. This fee is small enough so it does not significantly affect the cost of transaction, but large enough so it dissuades bad actors from spamming the network. \r\n\r\nPrior to Protocol 12, Stellar had a built-in inflation mechanism conceived to allow account holders to collectively direct inflation-generated lumens toward projects built on Stellar.\r\n\r\nAs the network evolved and grew, it became increasingly clear that inflation wasn’t working as intended — account holders either didn’t set their inflation destination or joined inflation pools to claim the inflation themselves, and the operational costs associated with inflation payments continued to rise — and so a protocol change to disable inflation was proposed, implemented, voted on by validators, and ultimately adopted as part of a network upgrade.\r\n\r\nThe inflation operation is now deprecated.\r\nhttps://developers.stellar.org/docs/glossary/inflation/\r\n',
    },
    links: {
      homepage: ["https://www.stellar.org/", "https://medium.com/stellar-community", ""],
      whitepaper: "",
      blockchain_site: [
        "https://dashboard.stellar.org/",
        "https://stellar.expert/explorer/public/",
        "https://steexp.com/",
        "https://blockchair.com/stellar",
        "https://explorer.energi.network/token/0xc0cd560393a3fad67486b10bbb461ed2a42dd882",
        "",
        "",
        "",
        "",
        "",
      ],
    },
    image: {
      thumb: "https://assets.coingecko.com/coins/images/100/thumb/Stellar_symbol_black_RGB.png?1696501482",
      small: "https://assets.coingecko.com/coins/images/100/small/Stellar_symbol_black_RGB.png?1696501482",
      large: "https://assets.coingecko.com/coins/images/100/large/Stellar_symbol_black_RGB.png?1696501482",
    },
  },
  {
    id: "ripple",
    symbol: "xrp",
    name: "XRP",
    web_slug: "xrp",
    categories: ["FTX Holdings", "Cryptocurrency"],
    description: {
      en: 'Ripple is the catchall name for the cryptocurrency platform, the transactional protocol for which is actually XRP, in the same fashion as <a href="https://www.coingecko.com/en/coins/ethereum">Ethereum</a> is the name for the platform that facilitates trades in Ether. Like other cryptocurrencies, Ripple is built atop the idea of a distributed ledger network which requires various parties to participate in validating transactions, rather than any singular centralized authority. That facilitates transactions all over the world, and transfer fees are far cheaper than the likes of bitcoin. Unlike other cryptocurrencies, XRP transfers are effectively immediate, requiring no typical confirmation time.\r\n\r\nRipple was originally founded by a single company, <a href="https://www.crunchbase.com/organization/ripple-labs">Ripple Labs</a>, and continues to be backed by it, rather than the larger network of developers that continue <a href="https://www.coingecko.com/en/coins/bitcoin">bitcoin’s</a> development. It also doesn’t have a fluctuating amount of its currency in existence. Where bitcoin has a continually growing pool with an eventual maximum, and Ethereum theoretically has no limit, Ripple was created with all of its 100 billion XRP tokens right out of the gate. That number is maintained with no mining and most of the tokens are owned and held by Ripple Labs itself — around 60 billion at the latest count.\r\n\r\nEven at the recently reduced value of around half a dollar per XRP, that means Ripple Labs is currently sitting on around $20 billion worth of the cryptocurrency (note: Ripple’s price crashed hard recently, and may be worth far less than $60 billion by time you read this). It holds 55 billion XRP in an escrow account, which allows it to sell up to a billion per month if it so chooses in order to fund new projects and acquisitions. Selling such an amount would likely have a drastic effect on the cryptocurrency’s value, and isn’t something Ripple Labs plans to do anytime soon.\r\n\r\nIn actuality, Ripple Labs is looking to leverage the technology behind XRP to allow for faster banking transactions around the world. While Bitcoin and other cryptocurrencies are built on the idea of separating financial transactions from the financial organizations of traditional currencies, Ripple is almost the opposite in every sense.\r\n\r\nXRP by Ripple price can be found on this page alongside the market capitalization and additional stats.\r\n\r\n',
    },
    links: {
      homepage: ["https://ripple.com/currency/", "", ""],
      whitepaper: "",
      blockchain_site: [
        "https://blockchair.com/ripple",
        "https://xrpcharts.ripple.com",
        "https://xrpscan.com/",
        "https://bithomp.com/explorer/",
        "",
        "",
        "",
        "",
        "",
        "",
      ],
    },
    image: {
      thumb: "https://assets.coingecko.com/coins/images/44/thumb/xrp-symbol-white-128.png?1696501442",
      small: "https://assets.coingecko.com/coins/images/44/small/xrp-symbol-white-128.png?1696501442",
      large: "https://assets.coingecko.com/coins/images/44/large/xrp-symbol-white-128.png?1696501442",
    },
  },
  {
    id: "tezos",
    symbol: "xtz",
    name: "Tezos",
    web_slug: "tezos",
    categories: ["Proof of Stake (PoS)", "Smart Contract Platform", "Layer 1 (L1)", "Tezos Ecosystem"],
    description: {
      en: "What Is Tezos (XTZ)?\r\n\r\n\r\nTezos is a high-performing blockchain and open-source platform for assets and applications, with a strong focus on code security, on-chain governance, and decentralization. Tezos 2.0, the upcoming step in the evolution of Tezos, aims to improve scalability (via layer 2s), composability, and to implement support to mainstream programming languages (like Javascript, Typescript, Python, and many others).\r\n\r\n\r\nInitially built with formal verification in mind, the Tezos protocol enables builders to avoid bugs when developing smart contracts, making it particularly suited to applications that require a high degree of security and certainty.\r\n\r\n\r\nTezos’ LPoS (Liquid Proof-of-Stake) consensus mechanism enables any stakeholder to take part, directly or by delegation, in the consensus process, and to be rewarded for securing the network. Rather uniquely, Tezos’ on-chain governance system also enables stakeholders to create and vote on protocol upgrade proposals. This pioneering system allows the protocol to self-amend and upgrade itself without leading to a split (or fork) in the blockchain, empowering the community without slowing down innovation.\r\n\r\n\r\nFirst proposed in 2014 and launched in 2018, the Tezos Mainnet has a proven track record of running uninterrupted ever since, having earned a strong reputation for technical excellence and a supportive community. \r\n\r\n\r\nWho Are the Founders of Tezos?\r\nTezos was conceived by Arthur and Kathleen Breitman in a 2014 white paper under the pseudonym L.M. Goodman in a nod to Satoshi Nakamoto, referencing a journalist who had misidentified the creator of Bitcoin.\r\n\r\n\r\nIn a previous paper, the Breitmans had argued that Bitcoin's biggest shortcomings were the lack of a governance process that invited contributions from its community of users, cost and centralization issues raised by its proof-of-work system, the limited expressiveness of its programming language which didn’t allow for smart contracts, and security ",
    },
    links: {
      homepage: ["https://www.tezos.com/", "https://tezos.foundation/", "https://wallet.kukai.app/"],
      whitepaper: "https://tezos.com/whitepaper.pdf",
      blockchain_site: [
        "https://tzstats.com/",
        "https://teztracker.com/en/mainnet/",
        "https://tezblock.io",
        "https://tzkt.io",
        "",
        "",
        "",
        "",
        "",
        "",
      ],
    },
    image: {
      thumb: "https://assets.coingecko.com/coins/images/976/thumb/Tezos-logo.png?1696502091",
      small: "https://assets.coingecko.com/coins/images/976/small/Tezos-logo.png?1696502091",
      large: "https://assets.coingecko.com/coins/images/976/large/Tezos-logo.png?1696502091",
    },
  },
];
